# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QCursor


class MianUI2(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 400)
        Form.setStyleSheet("border-bottom-right-radius:10px;\n"
                           "border-top-right-radius:10px;\n"
                           "border-top-left-radius:10px;\n"
                           "border-bottom-left-radius:10px;\n"
                           "background-color: rgb(255, 255, 255);")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setStyleSheet("background-color: rgb(239, 239, 239);\n"
                                    "border-bottom-right-radius:10px;\n"
                                    "border-top-right-radius:10px;\n"
                                    "border-top-left-radius:10px;\n"
                                    "border-bottom-left-radius:10px;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setSpacing(3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setMaximumSize(QtCore.QSize(22, 22))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap(":/vx/img/重命名.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_3.addWidget(self.label_14)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_3.addWidget(self.label_13)
        self.horizontalLayout_3.setStretch(0, 3)
        self.horizontalLayout_3.setStretch(1, 2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("border:none;\n"
                                      "border-bottom:0.9px solid rgb(0,0,0);\n"
                                      "\n"
                                      "border-bottom-right-radius:3px;\n"
                                      "border-top-right-radius:3px;\n"
                                      "border-top-left-radius:3px;\n"
                                      "border-bottom-left-radius:3px;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_4.addWidget(self.lineEdit_2)
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_13.setMaximumSize(QtCore.QSize(22, 22))
        self.pushButton_13.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.pushButton_13.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/vx/img/XLSX.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_13.setIcon(icon)
        self.pushButton_13.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_4.addWidget(self.pushButton_13)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setMaximumSize(QtCore.QSize(81, 21))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
                                        "    background-color: rgb(41, 159, 255);\n"
                                        "color: rgb(255,255,255);\n"
                                        "border:0.5px solid rgb(0,0,0);\n"
                                        "border-radius:3px;\n"
                                        "}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_5.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setMaximumSize(QtCore.QSize(81, 21))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
                                        "    background-color: rgb(41, 159, 255);\n"
                                        "color: rgb(255,255,255);\n"
                                        "border:0.5px solid rgb(0,0,0);\n"
                                        "border-radius:3px;\n"
                                        "}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_5.addWidget(self.pushButton_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setStyleSheet(
            "QProgressBar { border: 2px solid grey; border-radius: 5px; background-color: #FFFFFF; text-align: center;}QProgressBar::chunk {background:QLinearGradient(x1:0,y1:0,x2:2,y2:0,stop:0 #299FFF,stop:1  #87CEFA); }\"\n"
            "")
        self.progressBar.setProperty("value", 100)
        self.progressBar.setFormat("%p%")
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setStyleSheet("background-color: rgb(239, 239, 239);\n"
                                      "border-bottom-right-radius:10px;\n"
                                      "border-top-right-radius:10px;\n"
                                      "border-top-left-radius:10px;\n"
                                      "border-bottom-left-radius:10px;")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setMaximumSize(QtCore.QSize(22, 22))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap(":/vx/img/警告.png"))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_6.addWidget(self.label_18)
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_6.addWidget(self.label_17)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setMaximumSize(QtCore.QSize(81, 21))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
                                        "    background-color: rgb(41, 159, 255);\n"
                                        "color: rgb(255,255,255);\n"
                                        "border:0.5px solid rgb(0,0,0);\n"
                                        "border-radius:3px;\n"
                                        "}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_6.addWidget(self.pushButton_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.progressBar_2 = QtWidgets.QProgressBar(self.groupBox_2)
        self.progressBar_2.setStyleSheet(
            "QProgressBar { border: 2px solid grey; border-radius: 5px; background-color: #FFFFFF; text-align: center;}QProgressBar::chunk {background:QLinearGradient(x1:0,y1:0,x2:2,y2:0,stop:0 #299FFF,stop:1  #87CEFA); }\"\n"
            "")
        self.progressBar_2.setProperty("value", 100)
        self.progressBar_2.setVisible(True)
        self.progressBar_2.setFormat("%p%")
        self.progressBar_2.setObjectName("progressBar_2")
        self.verticalLayout_5.addWidget(self.progressBar_2)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_6.setStretch(0, 2)
        self.verticalLayout_6.setStretch(1, 4)
        self.verticalLayout_6.setStretch(2, 2)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 2)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setStyleSheet("background-color: rgb(239, 239, 239);\n"
                                      "border-bottom-right-radius:10px;\n"
                                      "border-top-right-radius:10px;\n"
                                      "border-top-left-radius:10px;\n"
                                      "border-bottom-left-radius:10px;")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_21 = QtWidgets.QLabel(self.groupBox_3)
        self.label_21.setMaximumSize(QtCore.QSize(22, 22))
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap(":/vx/img/文件.png"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_8.addWidget(self.label_21)
        self.label_20 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_8.addWidget(self.label_20)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("border:3px solid rgb(255, 255, 255);\n"
                                    "border-bottom-right-radius:5px;\n"
                                    "border-top-right-radius:5px;\n"
                                    "border-top-left-radius:5px;\n"
                                    "border-bottom-left-radius:5px;")
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 0, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setStyleSheet("border:3px solid rgb(255, 255, 255);\n"
                                      "border-bottom-right-radius:5px;\n"
                                      "border-top-right-radius:5px;\n"
                                      "border-top-left-radius:5px;\n"
                                      "border-bottom-left-radius:5px;")
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 0, 1, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setStyleSheet("border:3px solid rgb(255, 255, 255);\n"
                                      "border-bottom-right-radius:5px;\n"
                                      "border-top-right-radius:5px;\n"
                                      "border-top-left-radius:5px;\n"
                                      "border-bottom-left-radius:5px;")
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 1, 0, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setStyleSheet("border:3px solid rgb(255, 255, 255);\n"
                                      "border-bottom-right-radius:5px;\n"
                                      "border-top-right-radius:5px;\n"
                                      "border-top-left-radius:5px;\n"
                                      "border-bottom-left-radius:5px;")
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout.addWidget(self.checkBox_4, 1, 1, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout)
        self.verticalLayout_8.setStretch(0, 1)
        self.verticalLayout_8.setStretch(1, 5)
        self.gridLayout_2.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("border:none;\n"
                                      "border-bottom:0.9px solid rgb(0,0,0);\n"
                                      "\n"
                                      "border-bottom-right-radius:3px;\n"
                                      "border-top-right-radius:3px;\n"
                                      "border-top-left-radius:3px;\n"
                                      "border-bottom-left-radius:3px;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_9.addWidget(self.lineEdit_3)
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_14.setMaximumSize(QtCore.QSize(22, 22))
        self.pushButton_14.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.pushButton_14.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/vx/img/保存.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_14.setIcon(icon1)
        self.pushButton_14.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_9.addWidget(self.pushButton_14)
        self.verticalLayout_9.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_5.setMaximumSize(QtCore.QSize(81, 21))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
                                        "    background-color: rgb(41, 159, 255);\n"
                                        "color: rgb(255,255,255);\n"
                                        "border:0.5px solid rgb(0,0,0);\n"
                                        "border-radius:3px;\n"
                                        "}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_10.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_6.setMaximumSize(QtCore.QSize(81, 21))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
                                        "    background-color: rgb(41, 159, 255);\n"
                                        "color: rgb(255,255,255);\n"
                                        "border:0.5px solid rgb(0,0,0);\n"
                                        "border-radius:3px;\n"
                                        "}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_10.addWidget(self.pushButton_6)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        self.gridLayout_2.addLayout(self.verticalLayout_9, 0, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 2)
        self.gridLayout_2.setColumnStretch(1, 3)
        self.verticalLayout_7.addWidget(self.groupBox_3)
        self.groupBox_6 = QtWidgets.QGroupBox(Form)
        self.groupBox_6.setStyleSheet("background-color: rgb(239, 239, 239);\n"
                                      "border-bottom-right-radius:10px;\n"
                                      "border-top-right-radius:10px;\n"
                                      "border-top-left-radius:10px;\n"
                                      "border-bottom-left-radius:10px;")
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_7.setStyleSheet("background-color: rgb(245, 245, 245);\n"
                                      "border-bottom-right-radius:10px;\n"
                                      "border-top-right-radius:10px;\n"
                                      "border-top-left-radius:10px;\n"
                                      "border-bottom-left-radius:10px;")
        self.groupBox_7.setTitle("")
        self.groupBox_7.setMaximumSize(QtCore.QSize(431, 22))
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_2.setContentsMargins(5, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_23 = QtWidgets.QLabel(self.groupBox_7)
        self.label_23.setMinimumSize(QtCore.QSize(22, 22))
        self.label_23.setMaximumSize(QtCore.QSize(22, 22))
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap(":/vx/img/通知.png"))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_2.addWidget(self.label_23)
        self.label_22 = QtWidgets.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_2.addWidget(self.label_22)
        self.verticalLayout.addWidget(self.groupBox_7)
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_6)
        self.textEdit.setStyleSheet("border-bottom-right-radius:10px;\n"
                                    "border-top-right-radius:10px;\n"
                                    "border-top-left-radius:10px;\n"
                                    "border-bottom-left-radius:10px;\n"
                                    "background-color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.verticalLayout_7.addWidget(self.groupBox_6)
        self.verticalLayout_7.setStretch(0, 3)
        self.verticalLayout_7.setStretch(1, 2)
        self.verticalLayout_7.setStretch(2, 3)
        self.horizontalLayout_7.addLayout(self.verticalLayout_7)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("background-color: rgb(239, 239, 239);\n"
                                      "border-bottom-right-radius:10px;\n"
                                      "border-top-right-radius:10px;\n"
                                      "border-top-left-radius:10px;\n"
                                      "border-bottom-left-radius:10px;")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_4)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 36, 201, 53))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem)
        self.label_24 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_24.setMaximumSize(QtCore.QSize(51, 51))
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap(":/vx/img/icon.png"))
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_12.addWidget(self.label_24)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_4)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 90, 201, 61))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem2)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_25 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_10.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Book")
        font.setPointSize(9)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_10.addWidget(self.label_26)
        self.label_27 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Book")
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_10.addWidget(self.label_27)
        self.horizontalLayout_13.addLayout(self.verticalLayout_10)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem3)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_4)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 160, 201, 22))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem4)
        self.label_28 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Book")
        font.setPointSize(8)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("background-attachment: scroll;")
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_14.addWidget(self.label_28)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem5)
        self.widget = QtWidgets.QWidget(self.groupBox_4)
        self.widget.setGeometry(QtCore.QRect(9, 9, 200, 18))
        self.widget.setObjectName("widget")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(10)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("FANUC ASCII -European")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_11.addWidget(self.label_3)
        self.pushButton_8 = QtWidgets.QPushButton(self.widget)
        self.pushButton_8.setStyleSheet("QPushButton{\n"
                                        "    border:none;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "    padding-bottom:5px;\n"
                                        "}")
        self.pushButton_8.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/vx/img/叉删除.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon2)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_11.addWidget(self.pushButton_8)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(Form)
        self.groupBox_5.setStyleSheet("background-color: rgb(239, 239, 239);\n"
                                      "border-bottom-right-radius:10px;\n"
                                      "border-top-right-radius:10px;\n"
                                      "border-top-left-radius:10px;\n"
                                      "border-bottom-left-radius:10px;")
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_8.setStyleSheet("background-color: rgb(245, 245, 245);\n"
                                      "border-bottom-right-radius:10px;\n"
                                      "border-top-right-radius:10px;\n"
                                      "border-top-left-radius:10px;\n"
                                      "border-bottom-left-radius:10px;")
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_15.setContentsMargins(5, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_29 = QtWidgets.QLabel(self.groupBox_8)
        self.label_29.setMinimumSize(QtCore.QSize(22, 22))
        self.label_29.setMaximumSize(QtCore.QSize(22, 22))
        self.label_29.setText("")
        self.label_29.setPixmap(QtGui.QPixmap(":/vx/img/菜单管理.png"))
        self.label_29.setScaledContents(True)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_15.addWidget(self.label_29)
        self.label_30 = QtWidgets.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_15.addWidget(self.label_30)
        self.verticalLayout_12.addWidget(self.groupBox_8)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_11.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_11.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.groupBox_5)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_11.addWidget(self.label_6)
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_11.addWidget(self.radioButton)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSpacing(10)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_7.setMaximumSize(QtCore.QSize(81, 21))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
                                        "    background-color: rgb(41, 159, 255);\n"
                                        "color: rgb(255,255,255);\n"
                                        "border:0.5px solid rgb(0,0,0);\n"
                                        "border-radius:3px;\n"
                                        "}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_16.addWidget(self.pushButton_7)
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_9.setMaximumSize(QtCore.QSize(81, 21))
        self.pushButton_9.setStyleSheet("QPushButton{\n"
                                        "    background-color: rgb(41, 159, 255);\n"
                                        "color: rgb(255,255,255);\n"
                                        "border:0.5px solid rgb(0,0,0);\n"
                                        "border-radius:3px;\n"
                                        "}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_16.addWidget(self.pushButton_9)
        self.verticalLayout_12.addLayout(self.horizontalLayout_16)
        self.verticalLayout_12.setStretch(0, 1)
        self.verticalLayout_12.setStretch(1, 4)
        self.verticalLayout_12.setStretch(2, 1)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.horizontalLayout_7.setStretch(0, 4)
        self.horizontalLayout_7.setStretch(1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "发那科注释工具"))
        self.label_13.setText(_translate("Form", "注释修改："))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "点击右侧图标选择目录或自行指定一个xlsx文件"))
        self.pushButton_3.setText(_translate("Form", "清空"))
        self.pushButton_2.setText(_translate("Form", "执行"))
        self.label.setText(_translate("Form", "执行进度："))
        self.label_17.setText(_translate("Form", "注释删除："))
        self.pushButton_4.setText(_translate("Form", "执行"))
        self.label_2.setText(_translate("Form", "执行进度："))
        self.label_20.setText(_translate("Form", "生成IO表："))
        self.checkBox.setText(_translate("Form", "组IO"))
        self.checkBox_2.setText(_translate("Form", "数字IO"))
        self.checkBox_3.setText(_translate("Form", "机器人IO"))
        self.checkBox_4.setText(_translate("Form", "数值寄存器"))
        self.lineEdit_3.setPlaceholderText(_translate("Form", "点击右侧图标选择目录或自行指定一个目录"))
        self.pushButton_5.setText(_translate("Form", "全选"))
        self.pushButton_6.setText(_translate("Form", "执行"))
        self.label_22.setText(_translate("Form", "实时信息"))
        self.textEdit.setHtml(_translate("Form",
                                         "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                         "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                         "p, li { white-space: pre-wrap; }\n"
                                         "</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                         "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">----------------</p>\n"
                                         "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">如果是第一次使用</p>\n"
                                         "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">或者是需要帮助。</p>\n"
                                         "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">请点击左上角help</p>\n"
                                         "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">----------------</p>\n"
                                         "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'幼圆\'; font-size:6pt;\"><br /></p></body></html>"))
        self.label_25.setText(_translate("Form", "By 不知名网友"))
        self.label_26.setText(_translate("Form", "网址：www.vbzm.cn"))
        self.label_27.setText(_translate("Form", "bilibili：不知名网友i8"))
        self.label_28.setText(_translate("Form", "微信公众号:不知名网友i,欢迎关注"))
        self.label_3.setText(_translate("Form", "Fanuc Annotation tool"))
        self.label_30.setText(_translate("Form", "其他信息"))
        self.label_4.setText(_translate("Form", "当前连接IP地址："))
        self.label_5.setText(_translate("Form", "设备名称："))
        self.label_6.setText(_translate("Form", "当前版本："))
        self.radioButton.setText(_translate("Form", "Debug模式"))
        self.pushButton_7.setText(_translate("Form", "更换IP"))
        self.pushButton_9.setText(_translate("Form", "检查更新"))

        # 鼠标样式设置
        self.pushButton_2.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_3.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_4.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_5.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_6.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_7.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_8.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_9.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_13.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_14.setCursor(QCursor(Qt.PointingHandCursor))

        self.checkBox.setCursor(QCursor(Qt.PointingHandCursor))
        self.checkBox_2.setCursor(QCursor(Qt.PointingHandCursor))
        self.checkBox_3.setCursor(QCursor(Qt.PointingHandCursor))
        self.checkBox_4.setCursor(QCursor(Qt.PointingHandCursor))
        self.radioButton.setCursor(QCursor(Qt.PointingHandCursor))

        # 窗口操作
        self.pushButton_8.clicked.connect(Form.close)

        # 功能事件
        self.pushButton_2.clicked.connect(Form.while_note)
        self.pushButton_3.clicked.connect(Form.del_path)
        self.pushButton_4.clicked.connect(Form.del_note)
        self.pushButton_6.clicked.connect(Form.read_note)
        self.pushButton_5.clicked.connect(Form.all_select)

        self.pushButton_7.clicked.connect(Form.change_ip)
        self.pushButton_9.clicked.connect(Form.new_up)

        # 文件操作
        self.pushButton_14.clicked.connect(Form.selectPath)
        self.pushButton_13.clicked.connect(Form.selectFile)

        self.radioButton.clicked.connect(Form.debug_mode)

import img_rc
