# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zb.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QCursor


class ZBMian(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(690, 399)
        Form.setStyleSheet("border-bottom-right-radius:10px;\n"
                           "border-top-right-radius:10px;\n"
                           "border-top-left-radius:10px;\n"
                           "border-bottom-left-radius:10px;\n"
                           "background-color: rgb(255, 255, 255);")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setStyleSheet("#groupBox{\n"
                                    "background-color: rgb(239, 239, 239);\n"
                                    "border-bottom-right-radius:10px;\n"
                                    "border-top-right-radius:10px;\n"
                                    "border-top-left-radius:10px;\n"
                                    "border-bottom-left-radius:10px;\n"
                                    "}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_8.setStyleSheet("background-color: rgb(245, 245, 245);\n"
                                      "border-bottom-right-radius:10px;\n"
                                      "border-top-right-radius:10px;\n"
                                      "border-top-left-radius:10px;\n"
                                      "border-bottom-left-radius:10px;")
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_2.setContentsMargins(5, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_29 = QtWidgets.QLabel(self.groupBox_8)
        self.label_29.setMinimumSize(QtCore.QSize(22, 22))
        self.label_29.setMaximumSize(QtCore.QSize(22, 22))
        self.label_29.setText("")
        self.label_29.setPixmap(QtGui.QPixmap(":/vx/img/菜单管理.png"))
        self.label_29.setScaledContents(True)
        self.label_29.setObjectName("label_29")
        self.gridLayout_2.addWidget(self.label_29, 1, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.gridLayout_2.addWidget(self.label_30, 1, 1, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_8)
        self.doubleSpinBox.setDecimals(1)
        self.doubleSpinBox.setMinimum(0.1)
        self.doubleSpinBox.setMaximum(2.0)
        self.doubleSpinBox.setSingleStep(0.5)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout_2.addWidget(self.doubleSpinBox, 1, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 2, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_8)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 1, 3, 1, 1)
        self.gridLayout.addWidget(self.groupBox_8, 0, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_5.setSpacing(20)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_3.setStyleSheet("#groupBox_3{\n"
                                      "    background-color: rgb(229, 229, 229);\n"
                                      "}")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setMinimumSize(QtCore.QSize(90, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                 "border-top-right-radius:10px;\n"
                                 "border-top-left-radius:10px;\n"
                                 "border-bottom-right-radius:0px;\n"
                                 "border-bottom-left-radius:0px;")
        self.label.setTextFormat(QtCore.Qt.MarkdownText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setMinimumSize(QtCore.QSize(90, 24))
        self.label_2.setStyleSheet("background-color: rgb(245, 245, 245);\n"
                                   "border-top-right-radius:0px;\n"
                                   "border-top-left-radius:0px;\n"
                                   "border-bottom-right-radius:10px;\n"
                                   "border-bottom-left-radius:10px;\n"
                                   "color: rgb(41, 159, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setMinimumSize(QtCore.QSize(90, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                   "border-top-right-radius:10px;\n"
                                   "border-top-left-radius:10px;\n"
                                   "border-bottom-right-radius:0px;\n"
                                   "border-bottom-left-radius:0px;")
        self.label_3.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setMinimumSize(QtCore.QSize(90, 24))
        self.label_4.setStyleSheet("background-color: rgb(245, 245, 245);\n"
                                   "border-top-right-radius:0px;\n"
                                   "border-top-left-radius:0px;\n"
                                   "border-bottom-right-radius:10px;\n"
                                   "border-bottom-left-radius:10px;\n"
                                   "color: rgb(41, 159, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setMinimumSize(QtCore.QSize(90, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                   "border-top-right-radius:10px;\n"
                                   "border-top-left-radius:10px;\n"
                                   "border-bottom-right-radius:0px;\n"
                                   "border-bottom-left-radius:0px;")
        self.label_5.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setMinimumSize(QtCore.QSize(90, 24))
        self.label_6.setStyleSheet("background-color: rgb(245, 245, 245);\n"
                                   "border-top-right-radius:0px;\n"
                                   "border-top-left-radius:0px;\n"
                                   "border-bottom-right-radius:10px;\n"
                                   "border-bottom-left-radius:10px;\n"
                                   "\n"
                                   "\n"
                                   "color: rgb(255, 39, 125);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setMinimumSize(QtCore.QSize(90, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                   "border-top-right-radius:10px;\n"
                                   "border-top-left-radius:10px;\n"
                                   "border-bottom-right-radius:0px;\n"
                                   "border-bottom-left-radius:0px;")
        self.label_7.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setMinimumSize(QtCore.QSize(90, 24))
        self.label_8.setStyleSheet("background-color: rgb(245, 245, 245);\n"
                                   "border-top-right-radius:0px;\n"
                                   "border-top-left-radius:0px;\n"
                                   "border-bottom-right-radius:10px;\n"
                                   "border-bottom-left-radius:10px;\n"
                                   "color: rgb(41, 159, 255);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setMinimumSize(QtCore.QSize(90, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                   "border-top-right-radius:10px;\n"
                                   "border-top-left-radius:10px;\n"
                                   "border-bottom-right-radius:0px;\n"
                                   "border-bottom-left-radius:0px;")
        self.label_9.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_6.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setMinimumSize(QtCore.QSize(90, 24))
        self.label_10.setStyleSheet("background-color: rgb(245, 245, 245);\n"
                                    "border-top-right-radius:0px;\n"
                                    "border-top-left-radius:0px;\n"
                                    "border-bottom-right-radius:10px;\n"
                                    "border-bottom-left-radius:10px;\n"
                                    "color: rgb(41, 159, 255);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_6.addWidget(self.label_10)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setMinimumSize(QtCore.QSize(90, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                    "border-top-right-radius:10px;\n"
                                    "border-top-left-radius:10px;\n"
                                    "border-bottom-right-radius:0px;\n"
                                    "border-bottom-left-radius:0px;")
        self.label_11.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_7.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setMinimumSize(QtCore.QSize(90, 24))
        self.label_12.setStyleSheet("background-color: rgb(245, 245, 245);\n"
                                    "border-top-right-radius:0px;\n"
                                    "border-top-left-radius:0px;\n"
                                    "border-bottom-right-radius:10px;\n"
                                    "border-bottom-left-radius:10px;\n"
                                    "color: rgb(41, 159, 255);")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_7.addWidget(self.label_12)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_4.setStyleSheet("#groupBox_4{\n"
                                      "    background-color: rgb(229, 229, 229);\n"
                                      "}")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setMinimumSize(QtCore.QSize(90, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                    "border-top-right-radius:10px;\n"
                                    "border-top-left-radius:10px;\n"
                                    "border-bottom-right-radius:0px;\n"
                                    "border-bottom-left-radius:0px;")
        self.label_13.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_10.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setMinimumSize(QtCore.QSize(90, 24))
        self.label_14.setStyleSheet("background-color: rgb(245, 245, 245);\n"
                                    "border-top-right-radius:0px;\n"
                                    "border-top-left-radius:0px;\n"
                                    "border-bottom-right-radius:10px;\n"
                                    "border-bottom-left-radius:10px;\n"
                                    "color: rgb(41, 159, 255);")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_10.addWidget(self.label_14)
        self.horizontalLayout_3.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setMinimumSize(QtCore.QSize(90, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                    "border-top-right-radius:10px;\n"
                                    "border-top-left-radius:10px;\n"
                                    "border-bottom-right-radius:0px;\n"
                                    "border-bottom-left-radius:0px;")
        self.label_15.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_11.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setMinimumSize(QtCore.QSize(90, 24))
        self.label_16.setStyleSheet("background-color: rgb(245, 245, 245);\n"
                                    "border-top-right-radius:0px;\n"
                                    "border-top-left-radius:0px;\n"
                                    "border-bottom-right-radius:10px;\n"
                                    "border-bottom-left-radius:10px;\n"
                                    "color: rgb(41, 159, 255);")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_11.addWidget(self.label_16)
        self.horizontalLayout_3.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_17 = QtWidgets.QLabel(self.groupBox_4)
        self.label_17.setMinimumSize(QtCore.QSize(90, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                    "border-top-right-radius:10px;\n"
                                    "border-top-left-radius:10px;\n"
                                    "border-bottom-right-radius:0px;\n"
                                    "border-bottom-left-radius:0px;")
        self.label_17.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_12.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.groupBox_4)
        self.label_18.setMinimumSize(QtCore.QSize(90, 24))
        self.label_18.setStyleSheet("background-color: rgb(245, 245, 245);\n"
                                    "border-top-right-radius:0px;\n"
                                    "border-top-left-radius:0px;\n"
                                    "border-bottom-right-radius:10px;\n"
                                    "border-bottom-left-radius:10px;\n"
                                    "color: rgb(41, 159, 255);")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_12.addWidget(self.label_18)
        self.horizontalLayout_3.addLayout(self.verticalLayout_12)
        self.verticalLayout_9.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_19 = QtWidgets.QLabel(self.groupBox_4)
        self.label_19.setMinimumSize(QtCore.QSize(90, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                    "border-top-right-radius:10px;\n"
                                    "border-top-left-radius:10px;\n"
                                    "border-bottom-right-radius:0px;\n"
                                    "border-bottom-left-radius:0px;")
        self.label_19.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_13.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        self.label_20.setMinimumSize(QtCore.QSize(90, 24))
        self.label_20.setStyleSheet("background-color: rgb(245, 245, 245);\n"
                                    "border-top-right-radius:0px;\n"
                                    "border-top-left-radius:0px;\n"
                                    "border-bottom-right-radius:10px;\n"
                                    "border-bottom-left-radius:10px;\n"
                                    "color: rgb(41, 159, 255);")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_13.addWidget(self.label_20)
        self.horizontalLayout_4.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        self.label_21.setMinimumSize(QtCore.QSize(90, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                    "border-top-right-radius:10px;\n"
                                    "border-top-left-radius:10px;\n"
                                    "border-bottom-right-radius:0px;\n"
                                    "border-bottom-left-radius:0px;")
        self.label_21.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_14.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.groupBox_4)
        self.label_22.setMinimumSize(QtCore.QSize(90, 24))
        self.label_22.setStyleSheet("background-color: rgb(245, 245, 245);\n"
                                    "border-top-right-radius:0px;\n"
                                    "border-top-left-radius:0px;\n"
                                    "border-bottom-right-radius:10px;\n"
                                    "border-bottom-left-radius:10px;\n"
                                    "color: rgb(41, 159, 255);")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_14.addWidget(self.label_22)
        self.horizontalLayout_4.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_23 = QtWidgets.QLabel(self.groupBox_4)
        self.label_23.setMinimumSize(QtCore.QSize(90, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                    "border-top-right-radius:10px;\n"
                                    "border-top-left-radius:10px;\n"
                                    "border-bottom-right-radius:0px;\n"
                                    "border-bottom-left-radius:0px;")
        self.label_23.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_15.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.groupBox_4)
        self.label_24.setMinimumSize(QtCore.QSize(90, 24))
        self.label_24.setStyleSheet("background-color: rgb(245, 245, 245);\n"
                                    "border-top-right-radius:0px;\n"
                                    "border-top-left-radius:0px;\n"
                                    "border-bottom-right-radius:10px;\n"
                                    "border-bottom-left-radius:10px;\n"
                                    "color: rgb(41, 159, 255);")
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_15.addWidget(self.label_24)
        self.horizontalLayout_4.addLayout(self.verticalLayout_15)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addWidget(self.groupBox_4)
        self.gridLayout.addWidget(self.groupBox_5, 1, 0, 1, 1)
        self.verticalLayout_16.addWidget(self.groupBox)
        self.groupBox_7 = QtWidgets.QGroupBox(Form)
        self.groupBox_7.setStyleSheet("background-color: rgb(239, 239, 239);\n"
                                      "border-bottom-right-radius:10px;\n"
                                      "border-top-right-radius:10px;\n"
                                      "border-top-left-radius:10px;\n"
                                      "border-bottom-left-radius:10px;")
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_10.setStyleSheet("background-color: rgb(245, 245, 245);\n"
                                       "border-bottom-right-radius:10px;\n"
                                       "border-top-right-radius:10px;\n"
                                       "border-top-left-radius:10px;\n"
                                       "border-bottom-left-radius:10px;")
        self.groupBox_10.setTitle("")
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_6.setContentsMargins(5, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_57 = QtWidgets.QLabel(self.groupBox_10)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.gridLayout_6.addWidget(self.label_57, 1, 1, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.groupBox_10)
        self.label_58.setMinimumSize(QtCore.QSize(22, 22))
        self.label_58.setMaximumSize(QtCore.QSize(22, 22))
        self.label_58.setText("")
        self.label_58.setPixmap(QtGui.QPixmap(":/vx/img/重命名.png"))
        self.label_58.setScaledContents(True)
        self.label_58.setObjectName("label_58")
        self.gridLayout_6.addWidget(self.label_58, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_10, 0, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_7)
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_3.addWidget(self.textEdit, 1, 0, 1, 1)
        self.verticalLayout_16.addWidget(self.groupBox_7)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.move(0, 0)  # 设置窗口位置
        Form.setWindowTitle(_translate("Form", "机器人监控"))
        self.label_30.setText(_translate("Form", "机器人实时位置监控"))
        self.label_25.setText(_translate("Form", "刷新间隔调节"))
        self.label.setText(_translate("Form", "关节1度数"))
        self.label_2.setText(_translate("Form", "100.100"))
        self.label_3.setText(_translate("Form", "关节2度数"))
        self.label_4.setText(_translate("Form", "100.100"))
        self.label_5.setText(_translate("Form", "关节3度数"))
        self.label_6.setText(_translate("Form", "100.100"))
        self.label_7.setText(_translate("Form", "关节4度数"))
        self.label_8.setText(_translate("Form", "100.100"))
        self.label_9.setText(_translate("Form", "关节5度数"))
        self.label_10.setText(_translate("Form", "100.100"))
        self.label_11.setText(_translate("Form", "关节6度数"))
        self.label_12.setText(_translate("Form", "100.100"))
        self.label_13.setText(_translate("Form", "世界坐标X"))
        self.label_14.setText(_translate("Form", "100.100"))
        self.label_15.setText(_translate("Form", "世界坐标Y"))
        self.label_16.setText(_translate("Form", "100.100"))
        self.label_17.setText(_translate("Form", "世界坐标Z"))
        self.label_18.setText(_translate("Form", "100.100"))
        self.label_19.setText(_translate("Form", "世界坐标W"))
        self.label_20.setText(_translate("Form", "100.100"))
        self.label_21.setText(_translate("Form", "世界坐标P"))
        self.label_22.setText(_translate("Form", "100.100"))
        self.label_23.setText(_translate("Form", "世界坐标R"))
        self.label_24.setText(_translate("Form", "100.100"))
        self.label_57.setText(_translate("Form", "软件详细信息"))

        # 给doubleSpinBox绑定事件
        self.doubleSpinBox.valueChanged.connect(Form.Spbox)
        self.doubleSpinBox.setCursor(QCursor(Qt.PointingHandCursor))


import img_rc
